/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class FileSearchIndex {
  constructor(dbPath: string)
  rebuild(roots: Array<SearchRootInput>): Promise<IndexRebuildStatsDto>
  refresh(roots: Array<SearchRootInput>): Promise<IndexRefreshStatsDto>
  repair(roots: Array<SearchRootInput>): Promise<IndexRepairStatsDto>
  status(): Promise<Array<IndexRootStatusDto>>
  search(request: SearchRequest): Promise<IndexedSearchOutcomeDto>
}

export interface IndexedSearchOutcomeDto {
  candidateCount: number
  results: Array<SearchResultDto>
}

export interface IndexRebuildStatsDto {
  roots: number
  entries: number
  skipped: number
  errors: Array<string>
}

export interface IndexRefreshStatsDto {
  roots: number
  inserted: number
  updated: number
  deleted: number
  unchanged: number
  skipped: number
  errors: Array<string>
}

export interface IndexRepairStatsDto {
  roots: number
  dirtyRoots: number
  repairedRoots: number
  errors: Array<string>
}

export interface IndexRootStatusDto {
  path: string
  entryCount: number
  generation: number
  dirty: boolean
  lastFullScanAt?: number
  lastIncrementalAt?: number
}

export interface SearchRequest {
  roots: Array<SearchRootInput>
  query: string
  limit?: number
  includeHidden?: boolean
  includeIgnored?: boolean
  extensions?: Array<string>
}

export interface SearchResultDto {
  path: string
  score: number
  provider: string
  matches: Array<string>
}

export interface SearchRootInput {
  path: string
  enabled?: boolean
  priority?: number
  includeHidden?: boolean
  includeIgnored?: boolean
}
