nodeLinker: node-modules

packageExtensions:
  "@effect/platform-node@*":
    peerDependenciesMeta:
      "@effect/cluster":
        optional: true
      "@effect/rpc":
        optional: true
      "@effect/sql":
        optional: true
  "@effect/platform-node-shared@*":
    peerDependenciesMeta:
      "@effect/cluster":
        optional: true
      "@effect/rpc":
        optional: true
      "@effect/sql":
        optional: true
  "@opentui/core@*":
    dependencies:
      typescript: "^5.9.3"
