/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DirectoryTreeOptions {
  directories: Array<string>
  ignoreHidden?: boolean
  fullPath?: boolean
}
export interface Node {
  name: string
  size: number
  children: Array<Node>
  depth: number
}
export interface DisplayNode {
  name: string
  size: number
  children: Array<DisplayNode>
}
export declare function buildDirectoryTree(options: DirectoryTreeOptions): Array<Node>
export declare function getLargestNodes(nodes: Array<Node>, numberOfNodes: number): DisplayNode | null
