/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface DirectoryNode {
  name: string
  size: number
  children: Array<DirectoryNode>
  depth: number
  ignored: boolean
  collapsed: boolean
}

export interface DirectoryScanOptions {
  directories: Array<string>
  ignoreHidden?: boolean
  fullPath?: boolean
  respectGitignore?: boolean
  ignoredMode?: string
}

export declare function scanDirectory(options: DirectoryScanOptions): Array<DirectoryNode>
