/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CleanupCandidate {
  path: string
  size: number
  reason: string
  preset: string
  ignored: boolean
}

export interface CleanupCandidateOptions {
  directories: Array<string>
  presets?: Array<string>
  ignoreHidden?: boolean
}

export interface DirectoryNode {
  name: string
  path: string
  size: number
  children: Array<DirectoryNode>
  depth: number
  ignored: boolean
  collapsed: boolean
}

export interface DirectoryScanOptions {
  directories: Array<string>
  ignoreHidden?: boolean
  fullPath?: boolean
  respectGitignore?: boolean
  ignoredMode?: string
}

export declare function executeCleanup(plan: RemovalPlan): RemovalOutcome

export declare function findCleanupCandidates(options: CleanupCandidateOptions): Array<CleanupCandidate>

export declare function planCleanup(options: CleanupCandidateOptions): RemovalPlan

export interface RemovalEntry {
  path: string
  size: number
  reason: string
  preset: string
}

export interface RemovalOutcome {
  removed: Array<RemovalEntry>
  bytesRemoved: number
  errors: Array<string>
}

export interface RemovalPlan {
  entries: Array<RemovalEntry>
  totalSize: number
  errors: Array<string>
}

export declare function scanDirectory(options: DirectoryScanOptions): Array<DirectoryNode>
