/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ICloudSession {
  constructor()
  inspectICloudItem(path: string): ICloudItem
  planICloudEviction(root: string): ICloudPlan
  executeICloudEviction(planId: string): ICloudEvictionOutcome
  requestICloudDownload(path: string): void
}

export interface CleanupCandidate {
  path: string
  size: number
  reason: string
  preset: string
  ignored: boolean
}

export interface CleanupCandidateOptions {
  directories: Array<string>
  presets?: Array<string>
  ignoreHidden?: boolean
}

export declare function deletePath(path: string): void

export interface DirectoryNode {
  name: string
  path: string
  size: number
  children: Array<DirectoryNode>
  depth: number
  ignored: boolean
  collapsed: boolean
}

export interface DirectoryScanOptions {
  directories: Array<string>
  ignoreHidden?: boolean
  fullPath?: boolean
  respectGitignore?: boolean
  ignoredMode?: string
}

export declare function executeCleanup(plan: RemovalPlan): RemovalOutcome

export declare function findCleanupCandidates(options: CleanupCandidateOptions): Array<CleanupCandidate>

export interface ICloudEvictionOutcome {
  results: Array<ICloudEvictionResult>
}

export interface ICloudEvictionResult {
  path: string
  status: string
  allocatedBytesBefore: string
  error?: string
}

export interface ICloudItem {
  path: string
  kind: string
  isICloud: boolean
  downloadState: string
  logicalBytes: string
  allocatedBytes?: string
  foundationAllocatedBytes?: string
  isUploaded?: boolean
  isUploading?: boolean
  isDownloading?: boolean
  hasConflicts?: boolean
}

export interface ICloudPlan {
  planId: string
  root: string
  candidateCount: number
  allocatedBytes: string
  logicalBytes: string
  cloudOnlyCount: number
  skippedCount: number
  coverageComplete: boolean
}

export declare function planCleanup(options: CleanupCandidateOptions): RemovalPlan

export interface RemovalEntry {
  path: string
  size: number
  reason: string
  preset: string
}

export interface RemovalOutcome {
  removed: Array<RemovalEntry>
  bytesRemoved: number
  errors: Array<string>
}

export interface RemovalPlan {
  entries: Array<RemovalEntry>
  totalSize: number
  errors: Array<string>
}

export declare function scanDirectory(options: DirectoryScanOptions): Array<DirectoryNode>
