#!/usr/bin/env python3
"""Render the Homebrew cask from the real app-v* release artifacts.

Runs in CI (workbench.yml brew-tap job). Reads the downloaded dmg files,
computes sha256, and writes the final cask to /tmp/space-lens.rb, ready to be
copied into HuakunShen/homebrew-tap.
"""
import glob
import hashlib
import os
import sys
import urllib.parse

version = os.environ["VERSION_REF"].removeprefix("app-v")
repo = os.environ["REPO"]

arm = x64 = None
for dmg in sorted(glob.glob("/tmp/dmg/*.dmg")):
    name = os.path.basename(dmg)
    sha = hashlib.sha256(open(dmg, "rb").read()).hexdigest()
    if "aarch64" in name:
        arm = (sha, name)
    elif "x64" in name:
        x64 = (sha, name)
if arm is None or x64 is None:
    sys.exit(f"missing dmg artifacts: arm={arm} x64={x64}")


def asset_url(name: str) -> str:
    return (
        f"https://github.com/{repo}/releases/download/app-v{version}/"
        + urllib.parse.quote(name)
    )


cask = """# Generated by workbench.yml (brew-tap job) from the app-v__VERSION__ release.
# Source of truth: packaging/homebrew/Casks/space-lens.rb in the space-lens repo.
cask "space-lens" do
  arch arm: "aarch64", intel: "x64"

  version "__VERSION__"
  sha256 arm:   "__ARM_SHA__",
         intel: "__X64_SHA__"

  url arm:   "__ARM_URL__",
      intel: "__X64_URL__"
  name "Space Lens"
  desc "Local-first disk map: scan any folder and stage cleanup candidates"
  homepage "https://github.com/__REPO__"

  livecheck do
    url "https://github.com/__REPO__/releases/latest"
    strategy :github_latest do |json|
      json["tag_name"]&.sub(/^app-v/, "")
    end
  end

  auto_updates true

  app "Space Lens.app"

  zap trash: [
    "~/Library/Application Support/sh.huakun.spacelens.desktop",
    "~/Library/WebKit/sh.huakun.spacelens.desktop",
  ]
end
"""
cask = (
    cask.replace("__VERSION__", version)
    .replace("__ARM_SHA__", arm[0])
    .replace("__X64_SHA__", x64[0])
    .replace("__ARM_URL__", asset_url(arm[1]))
    .replace("__X64_URL__", asset_url(x64[1]))
    .replace("__REPO__", repo)
)

out = "/tmp/space-lens.rb"
with open(out, "w") as handle:
    handle.write(cask)
print(f"wrote {out} ({len(cask)} bytes)")
